package com.kelompoksatu.hris.utils;

public enum TestScenarios {

    // LOGIN
    T1("TCC.Tele.Login.001 User invalid login") ,
    T2("TCC.Tele.Login.004 User invalid login username kosong"),
    T3("TCC.Tele.Login.005 User invalid login password kosong"),
    T4("TCC.Tele.Login.006 User invalid login username invalid"),
    T5("TCC.Tele.Login.007 User invalid login password invalid"),
    T6("TCC.Tele.Login.003 User invalid login username password kosong"),
    T7("TCC.Tele.Login.007 User valid login"),
    T8("TCC.Tele.001 Upload data isi"),

    // UPLOAD DATA
    T9("TCC.Tele.001 Upload data isi"),
    T10("TCC.Tele.002 Upload data kosong"),
    T11("TCC.Tele.003 Simpan data kosong"),
    T12("TCC.Tele.004 Upload data file txt"),
    T13("TCC.Tele.005 Simpan data file txt"),

    //DISTRIBUTE DATA
    T14("TCC.Tele.Distribusi.001 Add Distribusi Data"),
    T15("TCC.Tele.Distribusi.002 view distribusi data"),
    T16("TCC.Tele.Distribusi.003 page 2"),
    T17("TCC.Tele.Distribusi.004 last page"),
    T18("TCC.Tele.Distribusi.005 first page"),
    T19("TCC.Tele.Distribusi.006 page 25"),
    T20 ("TCC.Tele.Distribusi.007 page 50"),
    T21("TCC.Tele.Distribusi.008 page 100"),
    T22("TCC.Tele.Distribusi.009 page 500"),
    T23("TCC.Tele.Distribusi.010 page 10"),
    T24("TCC.Tele.011 Unchecklist status dan buket data"),
    T25("TCC.Tele.012 Unchecklist status"),
    T26("TCC.Tele.013 Unchecklist buket data"),
    T27("TCC.Tele.014 Kosongkan distribusi dan jumlah agent"),
    T28("TCC.Tele.015 Kosongkan distribusi"),
    T29("TCC.Tele.016 Kosongkan jumlah agent"),

    //EDIT DATA
    T30("TCC.Tele.001 Tidak Masuk halaman edit data"),
    T31("TCC.Tele.002.EditData Tidak menginputkan data dan klik search"),
    T32("TCC.Tele.003.EditData Search input sempurna"),
    T33("TCC.EDIT DATA SEARCH.004 input telero"),
    T34("TCC.EDIT DATA SEARCH.005 page 2"),
    T35("TCC.EDIT DATA SEARCH.006 last page"),
    T36("TCC.EDIT DATA SEARCH.007 first page"),
    T37("TCC.EDIT DATA SEARCH.008 page 25"),
    T38("TCC.EDIT DATA SEARCH.009 page 50"),
    T39("TCC.EDIT DATA SEARCH.010 page 100"),
    T40("TCC.EDIT DATA SEARCH.010 page 500"),
    T41("TCC.EDIT DATA SEARCH.010 page 10"),
    T42("TCC.EDIT DATA SEARCH.013 edit data"),
    T43("TCC.Tele.Login.008 User logout"),


    //USER MANAGEMENT
    T44("TCC.USERMANAGEMENT.001 Tekan button User Management"),
    T45("TCC.USERMANAGEMENT.002 Tekan button User"),
    T46("TCC.USERMANAGEMENT.003 Tidak ada data dan klik search"),
    T47("TCC.USERMANAGEMENT.004 Search Data Terdaftar"),
    T48("TCC.USERMANAGEMENT.006 Menampilkan form add"),
    T49("TCC.USERMANAGEMENT.007 menyimpan tanpa data agent"),
    T50("TCC.USERMANAGEMENT.008 Mengisi data tanpa memilih privileges dikolom"),
    T51("TCC.USERMANAGEMENT.009 Mengisi data memilih privileges agent dikolom"),
    T52("TCC.USERMANAGEMENT.010 Mengisi data memilih privileges admin dikolom"),
    T53("TCC.USERMANAGEMENT.011 Mengisi data tanpa memilih Supervisor dikolom"),
    T54("TCC.USERMANAGEMENT.012 Mengisi data memilih Supervisor dikolom"),
    T55("TCC.USERMANAGEMENT.013 Mengisi full name dengan angka"),
    T56("TCC.USERMANAGEMENT.014 Menekan button Reset Password"),
    T57("TCC.USERMANAGEMENT.015 Memilih data yang akan direset"),

    //Login Agent
    T58 ("TCC.Tele.001 Input username dan password invalid"),
    T59 ("TCC.Tele.002 Input username valid dan password invalid"),
    T60 ("TCC.Tele.003 Input username invalid dan password valid"),
    T61 ("TCC.Tele.005 Input username dan password valid"),
    T62 ("TCC.Tele.006 Logout"),
    T63 ("TCC.Tele.007 Input username huruf kapital dan password valid"),

    //Agent New
    T64 ("Input username dan password valid"),
    T65 ("TCC.Tele.001 Masuk halaman task new"),
    T66 ("TCC.Tele.002 Mencari data huruf"),
    T67 ("TCC.Tele.003 Mencari data kosong"),
    T68 ("TCC.Tele.004 Mencari data angka"),
    T69 ("TCC.Tele.005 Mencari data simbol"),
    T70 ("Mencari data dan memunculkan data halaman berikutnya"),
    T71 ("TCC.Tele.007 Menampilkan 10 data per halaman"),
    T72 ("TCC.Tele.008 Menampilkan 50 data per halaman"),
    T73 ("TCC.Tele.009 Menampilkan 10 data per halaman"),
    T74 ("TCC.Tele.010 Menampilkan data urutan sesuai halaman"),
    T75 ("TCC.Tele.011 Menampilkan data halaman terakhir"),
    T76 ("TCC.Tele.012 Menampilkan data halaman pertama"),
    T77 ("TCC.Tele.013 Add nomor telepon"),
    T78 ("TCC.Tele.014 Add nomor telepon lebih dari lima belas karakter"),
    T79 ("TCC.Tele.015 Tidak input nomor telepon"),
    T80 ("TCC.Tele.016 Tidak input data edit activity"),
    T81 ("TCC.Tele.017 Hanya edit activity channel"),
    T82 ("TCC.Tele.018 Hanya edit activity channel dan status"),
    T83 ("TCC.Tele.019 Hanya edit activity channel dan status dan status call"),
    T84 ("TCC.Tele.020 Edit activity channel dan status dan status call dan status result"),
    T85 ("TCC.Tele.021 Edit activity channel dan status dan status call dan status result dan reason"),

    //Agent New
    T86 ("TCC.Tele.022 Masuk halaman task agree"),
    T87 ("TCC.Tele.023 Mencari data huruf"),
    T88 ("TCC.Tele.024 Mencari data kosong"),
    T89 ("TCC.Tele.025 Mencari data angka"),
    T90 ("TCC.Tele.026 Mencari data simbol"),
    T91 ("TCC.Tele.027 Mencari data dan memunculkan data halaman berikutnya"),
    T92 ("TCC.Tele.028 Menampilkan 25 data per halaman"),
    T93 ("TCC.Tele.029 Menampilkan 10 data per halaman"),
    T94 ("TCC.Tele.030 Menampilkan data urutan sesuai halaman"),
    T95 ("TCC.Tele.031 Menampilkan data halaman terakhir"),
    T96 ("TCC.Tele.032 Menampilkan data halaman pertama"),
    T97 ("TCC.Tele.033 Link berhasil terupdate"),
    T98 ("TCC.Tele.034 Update link kosong"),

    //REPORT AGREE
    T99("TCC.Tele.001 Masuk halaman report agree"),
    T100("TCC.Tele.001.Agree.View Memasukkan start date dan end date"),
    T101("TCC.Tele.002.Agree.View Tidak memasukkan tanggal awal dan akhir"),
    T102("TCC.Tele.003.Agree.View Memasukkan start date"),
    T103("TCC.Tele.004.Agree.View Memasukkan end date"),
    T104("TCC.Tele.001.Agree.Export Memasukkan start date dan end date"),
    T105("TCC.Tele.002.Agree.Export Tidak memasukkan start date dan end date"),
    T106("TCC.Tele.001.Agree.Showpage show entries 10"),
    T107("TCC.Tele.002.Agree.Showpage show entries 25"),
    T108("TCC.Tele.003.Agree.Showpage show entries 50"),
    T109("TCC.Tele.004.Agree.Showpage show entries 100"),
    T110("TCC.Tele.001.Agree.Nextpage show page 2"),
    T111("TCC.Tele.002.Agree.Nextpage show last page"),
    T112("TCC.Tele.003.Agree.Nextpage show first page"),

    //REPORT ACTIVITY
    T113("TCC.Tele.001.Report.Activity Masuk halaman report activity"),
    T114("TCC.Tele.001.Activity.View Memilih agent dan tanggal"),
    T115("TCC.Tele.002.Activity.View Memilih tanggal dan tidak memilih agent"),
    T116("TCC.Tele.001.Activity.Export Export data setelah memilih agent dan memasukkan tanggal awal dan akhir"),
    T117("TCC.Tele.002.Activity.Export Export data tanpa memilih agent dan memasukkan tanggal awal dan akhir"),
    T118("TCC.Tele.001.Activity.Showpage Show entries 10"),
    T119("TCC.Tele.001.Activity.Nextpage Show page 2"),
    T120("TCC.Tele.002.Activity.Nextpage Show lastpage"),
    T121("TCC.Tele.003.Activity.Nextpage Show firstpage"),

    //TASK FOLLOW UP
    T122("TCC.Tele.001.Task.FollowUp Masuk halaman task follow up"),
    T123("TCC.Tele.001.Task.FollowUp.Search Input data klik search"),
    T124("TCC.Tele.002.Task.FollowUp.Search input data berupa angka klik search"),
    T125("TCC.Tele.003.Task.FollowUp.Search input data berupa simbol klik search"),
    T126("TCC.Tele.004.Task.FollowUp.Search tidak input data klik search"),
    T127("TCC.Tele.001.Task.FollowUp.Showpage show enties 10"),
    T128("TCC.Tele.001.Task.FollowUp.Nextpage show page 2"),
    T129("TCC.Tele.002.Task.FollowUp.Nextpage show lastpage"),
    T130("TCC.Tele.003.Task.FollowUp.Nextpage show first page"),
    T131("TCC.Tele.001.Task.FollowUp.Edit input nomor telepon"),
    T132("TCC.Tele.002.Task.FollowUp.Edit input nomor telepon lebih dari 15 karakter"),
    T134("TCC.Tele.003.Task.FollowUp.Edit input nomor telepon dengan huruf"),
    T135("TCC.Tele.004.Task.FollowUp.Edit tidak input nomor telepon"),
    T136("TCC.Tele.005.Task.FollowUp.Edit tidak input data klik submit"),
    T137("TCC.Tele.006.Task.FollowUp.Edit memilih channel"),
    T138("TCC.Tele.007.Task.FollowUp.Edit memilih channel dan status"),
    T139("TCC.Tele.008.Task.FollowUp.Edit memilih channel, status dan status call"),
    T140("TCC.Tele.009.Task.FollowUp.Edit memilih channel, status, status call dan status result"),
    T141("TCC.Tele.010.Task.FollowUp.Edit memilih channel, status, status call, status result dan reason"),
    T142("TCC.Tele.011.Task.FollowUp.Edit pilih phone, edit status activity, klik submit"),

    //TASK DATA ALL
    T143("TCC.Tele.001.Task.All masuk halaman task data all"),
    T144("TCC.Tele.001.Task.All.Search search hanya memilih customer"),
    T145("TCC.Tele.002.Task.All.Search search hanya memilih agent"),
    T146("TCC.Tele.003.Task.All.Search search hanya memilih status"),
    T147("TCC.Tele.004.Task.All.Search search hanya memilih customer dan agent"),
    T148("TCC.Tele.005.Task.All.Search search hanya memilih status dan agent"),
    T149("TCC.Tele.006.Task.All.Search search hanya memilih customer dan status"),
    T150("TCC.Tele.007.Task.All.Search search hanya memilih customer, agent dan status"),
    T151("TCC.Tele.008.Task.All.Search Search dikosongkan"),
    T152("TCC.Tele.001.Task.All.Showpage show entries 10"),
    T153("TCC.Tele.001.Task.All.Showpage show entries 25"),
    T154("TCC.Tele.001.Task.All.Showpage show entries 50"),
    T155("TCC.Tele.001.Task.All.Showpage show entries 100"),
    T156("TCC.Tele.001.Task.All.NextPage show page 2"),
    T157("TCC.Tele.002.Task.All.NextPage show lastpage"),
    T158("TCC.Tele.003.Task.All.NextPage show first page"),
    T159("TCC.Tele.001.Task.All.Edit input nomor telepon"),
    T160("TCC.Tele.002.Task.All.Edit input nomor telepon lebih dari 15 karakter"),
    T161("TCC.Tele.003.Task.All.Edit input nomor telepon dengan huruf"),
    T162("TCC.Tele.004.Task.All.Edit tidak input nomor telepon"),
    T163("TCC.Tele.005.Task.All.Edit tidak input data klik submit"),
    T164("TCC.Tele.006.Task.All.Edit memilih channel"),
    T165("TCC.Tele.007.Task.All.Edit memilih channel dan status"),
    T166("TCC.Tele.008.Task.All.Edit memilih channel, status dan status call"),
    T167("TCC.Tele.009.Task.All.Edit memilih channel, status, status call dan status result"),
    T168("TCC.Tele.010.Task.All.Edit memilih channel, status, status call, status result dan reason"),
    T169("TCC.Tele.011.Task.All.Edit pilih phone, edit status activity, klik submit"),

    //TASK  FINAL
    T170("TCC.Tele.001.Task.Final masuk halaman task final"),
    T171("TCC.Tele.001.Task.Final.Search Input data klik search"),
    T172("TCC.Tele.002.Task.Final.Search input data berupa angka klik search"),
    T173("TCC.Tele.003.Task.Final.Search input data berupa simbol klik search"),
    T174("TCC.Tele.004.Task.Final.Search tidak input data klik search"),
    T175("TCC.Tele.001.Task.Final.Showpage show entries 10"),
    T176("TCC.Tele.002.Task.Final.Showpage show entries 25"),
    T177("TCC.Tele.001.Task.Final.Nextpage show page 2"),
    T178("TCC.Tele.002.Task.Final.Nextpage show lastpage"),
    T179("TCC.Tele.003.Task.Final.Nextpage show first page"),

    //PHONE APPROVE
    T180("TCC.Tele.001.PhoneApprove mengakses user management"),
    T181("TCC.Tele.002.PhoneApprove menuju halaman phone approve"),
    T182("TCC.Tele.003.PhoneApprove tidak menginputkan search agent"),
    T183("TCC.Tele.004.PhoneApprove mencari data user yang terdaftar"),
    T184("TCC.Tele.005.PhoneApprove mencari data user yang belum terdaftar"),
    T185("TCC.Tele.006.PhoneApprove klik approve nomor"),
    T186("TCC.Tele.007.PhoneApprove klik approve nomor yes"),
    T187("TCC.Tele.008.PhoneApprove klik approve nomor no"),
    T188("TCC.Tele.009.PhoneApprove klik reject nomor"),
    T189("TCC.Tele.010.PhoneApprove mereject user yang ditentukan"),
    T190("TCC.Tele.011.PhoneApprove batal reject user yang ditentukan"),
    T191("TCC.Tele.012.PhoneApprove show entries 10"),
    T192("TCC.Tele.013.PhoneApprove show entries 25"),
    T193("TCC.Tele.014.PhoneApprove show entries 50"),
    T194("TCC.Tele.015.PhoneApprove menampilkan grid agent"),
    T195("TCC.Tele.016.PhoneApprove menampilkan grid number phone"),
    T196("TCC.Tele.017.PhoneApprove menampilkan grid tanggal request"),
    T197("TCC.Tele.018.PhoneApprove menampilkan grid nama"),
    T198("TCC.Tele.019.PhoneApprove menampilkan grid status"),
    ;

    private String testName;

    TestScenarios(String value) {
        testName = value;
    }

    public String getTestName() {
        return testName;
    }

}

